"""
PDF Report Generator for AuraNova AI.
"""

from io import BytesIO

from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import Paragraph
from reportlab.platypus import SimpleDocTemplate
from reportlab.platypus import Spacer


def remove_emojis(text):
    """
    Remove emojis from strings before generating PDF.
    """

    if not text:
        return ""

    replacements = [
        "🟢 ",
        "🟡 ",
        "🔴 ",
        "🚨 ",
        "👨‍⚕️ ",
        "🧠 ",
        "🩺 ",
        "🫁 ",
        "👂 ",
        "🦴 ",
        "🚑 "
    ]

    for item in replacements:
        text = text.replace(item, "")

    return text


def generate_ai_report(report):
    """
    Generate AI Health Report PDF.
    """

    buffer = BytesIO()

    doc = SimpleDocTemplate(buffer)

    styles = getSampleStyleSheet()

    story = []

    # ----------------------------
    # Title
    # ----------------------------

    story.append(
        Paragraph(
            "<b>AuraNova AI Health Report</b>",
            styles["Title"]
        )
    )

    story.append(Spacer(1, 20))

    # ----------------------------
    # Symptoms
    # ----------------------------

    detected = report.get("detected", [])

    story.append(
        Paragraph(
            "<b>Detected Symptoms:</b> "
            + ", ".join(detected),
            styles["BodyText"]
        )
    )

    story.append(Spacer(1, 10))

    # ----------------------------
    # Condition
    # ----------------------------

    story.append(
        Paragraph(
            "<b>Possible Condition:</b> "
            + report.get("condition", ""),
            styles["BodyText"]
        )
    )

    story.append(Spacer(1, 10))

    # ----------------------------
    # Severity
    # ----------------------------

    story.append(
        Paragraph(
            "<b>Severity:</b> "
            + remove_emojis(report.get("severity", "")),
            styles["BodyText"]
        )
    )

    story.append(Spacer(1, 10))

    # ----------------------------
    # Doctor
    # ----------------------------

    story.append(
        Paragraph(
            "<b>Recommended Specialist:</b> "
            + remove_emojis(report.get("doctor", "")),
            styles["BodyText"]
        )
    )

    story.append(Spacer(1, 15))

    # ----------------------------
    # Advice
    # ----------------------------

    story.append(
        Paragraph(
            "<b>Recommended Care</b>",
            styles["Heading2"]
        )
    )

    for advice in report.get("advice", []):
        story.append(
            Paragraph(
                f"• {advice}",
                styles["BodyText"]
            )
        )

    # ----------------------------
    # Medicines
    # ----------------------------

    medicines = report.get("medicines", [])

    if medicines:

        story.append(Spacer(1, 15))

        story.append(
            Paragraph(
                "<b>Suggested OTC Care</b>",
                styles["Heading2"]
            )
        )

        for medicine in medicines:
            story.append(
                Paragraph(
                    f"• {medicine}",
                    styles["BodyText"]
                )
            )

    # ----------------------------
    # Disclaimer
    # ----------------------------

    story.append(Spacer(1, 20))

    story.append(
        Paragraph(
            "<b>Medical Disclaimer:</b><br/>"
            "This report is generated by AuraNova AI for "
            "preliminary guidance only. "
            "It is not a medical diagnosis. "
            "Please consult a qualified healthcare professional "
            "for proper diagnosis and treatment.",
            styles["Italic"]
        )
    )

    # ----------------------------
    # Build PDF
    # ----------------------------

    doc.build(story)

    buffer.seek(0)

    return buffer