from io import BytesIO

from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import SimpleDocTemplate
from reportlab.platypus import Paragraph
from reportlab.platypus import Spacer


def generate_ai_report(report):

    buffer = BytesIO()

    doc = SimpleDocTemplate(buffer)

    styles = getSampleStyleSheet()

    story = []

    story.append(
        Paragraph("<b>AuraNova AI Health Report</b>", styles["Title"])
    )

    story.append(Spacer(1, 20))

    story.append(
        Paragraph(
            f"<b>Detected Symptoms:</b> {', '.join(report['detected'])}",
            styles["BodyText"]
        )
    )

    story.append(Spacer(1, 10))

    story.append(
        Paragraph(
            f"<b>Possible Condition:</b> {report['condition']}",
            styles["BodyText"]
        )
    )

    story.append(Spacer(1, 10))

    story.append(
        Paragraph(
            f"<b>Severity:</b> {report['severity']}",
            styles["BodyText"]
        )
    )

    story.append(Spacer(1, 10))

    story.append(
        Paragraph(
            f"<b>Recommended Specialist:</b> {report['doctor']}",
            styles["BodyText"]
        )
    )

    story.append(Spacer(1, 10))

    story.append(
        Paragraph("<b>Recommended Care</b>", styles["Heading2"])
    )

    for advice in report["advice"]:

        story.append(
            Paragraph(f"• {advice}", styles["BodyText"])
        )

    if report.get("medicines"):

        story.append(Spacer(1, 15))

        story.append(
            Paragraph("<b>Suggested OTC Care</b>", styles["Heading2"])
        )

        for medicine in report["medicines"]:

            story.append(
                Paragraph(f"• {medicine}", styles["BodyText"])
            )

    story.append(Spacer(1, 20))

    story.append(
        Paragraph(
            "<b>Medical Disclaimer:</b> "
            "This report is generated by AuraNova AI and is only for "
            "preliminary guidance. Please consult a qualified healthcare "
            "professional for diagnosis and treatment.",
            styles["Italic"]
        )
    )

    doc.build(story)

    buffer.seek(0)

    return buffer